### ISSUE TITLE
Adapter crashes after update to 1.13.0

### ISSUE THREAD

**Issue by peer69** [ioBroker/ioBroker.sql#120]
After upgrading to 1.13.0 my adapter crashed on startup, going back to 1.12.5 fixes the error: 

```
sql.0 | 2020-05-18 17:29:22.910 | error | (3871) adapter disabled

sql.0 | 2020-05-18 17:28:51.628 | info | (3123) Terminated (NO_ERROR): Without reason

sql.0 | 2020-05-18 17:28:51.628 | info | (3123) terminating

sql.0 | 2020-05-18 17:28:51.123 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)

sql.0 | 2020-05-18 17:28:51.123 | error | at _0x30230c._applyViewFunc (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:115328)

sql.0 | 2020-05-18 17:28:51.123 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1482:21

sql.0 | 2020-05-18 17:28:51.123 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:7066:26

sql.0 | 2020-05-18 17:28:51.123 | error | at Array.map (<anonymous>)

sql.0 | 2020-05-18 17:28:51.123 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:7066:39

sql.0 | 2020-05-18 17:28:51.123 | error | (3123) TypeError: Cannot read property 'startsWith' of undefined

sql.0 | 2020-05-18 17:28:51.118 | error | (3123) unhandled promise rejection: Cannot read property 'startsWith' of undefined

sql.0 | 2020-05-18 17:28:51.048 | info | (3123) enabled logging of zwave.0.NODE6.METER.Electric_-_W_1, Alias=false, 16 points now activated
```

**Comment by Apollon77** [comment]
which js-controller version?

**Comment by peer69** [comment]
3.1.4

**Comment by Apollon77** [comment]
interesting ...
@ioBroker/developers 

 reason is a subscribeForeignState with an array where one element is undefined

**Comment by Apollon77** [comment]
https://github.com/ioBroker/ioBroker.sql/commit/58d3e279d5c9cd83e435c4eee552b570e3587c5f#diff-7a9076d6d94e62c13d641aa71f19ae8eR2557 :-(

**Comment by Apollon77** [comment]
PS: was also buggy before because on undefined entries it simply subscribed * ... but now we throw an error

**Comment by Superwuzy** [comment]
I've experienced the same problem since updated to 1.13.0 (js-controller 3.1.4).

**Comment by LJSven** [comment]
Same here

**Comment by kugelkopf123** [comment]
Same here! 
Always restarting...
```
2020-05-18 21:55:24.988  - [31merror[39m: sql.0 (32736) Error: ER_CON_COUNT_ERROR: Too many connections
2020-05-18 21:55:24.994  - [31merror[39m: sql.0 (32736) Error: ER_CON_COUNT_ERROR: Too many connections
2020-05-18 21:55:25.000  - [31merror[39m: sql.0 (32736) Error: ER_CON_COUNT_ERROR: Too many connections
2020-05-18 21:55:25.014  - [31merror[39m: sql.0 (32736) Error: ER_CON_COUNT_ERROR: Too many connections
2020-05-18 21:55:25.133  - [33mwarn[39m: sql.0 (32736) Terminated (UNCAUGHT_EXCEPTION): Without reason
2020-05-18 21:55:25.541  - [32minfo[39m: sql.0 (32736) terminating
2020-05-18 21:55:25.545  - [32minfo[39m: sql.0 (32736) terminating with timeout
2020-05-18 21:55:25.618  - [31merror[39m: sql.0 (32736) Error: ER_CON_COUNT_ERROR: Too many connections
2020-05-18 21:55:27.706  - [31merror[39m: host.raspi4 Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2020-05-18 21:55:27.709  - [31merror[39m: host.raspi4 Caught by controller[1]: TypeError: Cannot read property 'startsWith' of undefined
2020-05-18 21:55:27.710  - [31merror[39m: host.raspi4 Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:7066:39
2020-05-18 21:55:27.711  - [31merror[39m: host.raspi4 Caught by controller[1]:     at Array.map (<anonymous>)
2020-05-18 21:55:27.711  - [31merror[39m: host.raspi4 Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:7066:26
2020-05-18 21:55:27.712  - [31merror[39m: host.raspi4 Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:1482:21
2020-05-18 21:55:27.713  - [31merror[39m: host.raspi4 Caught by controller[1]:     at _0x30230c._applyViewFunc (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:115328)
2020-05-18 21:55:27.714  - [31merror[39m: host.raspi4 Caught by controller[1]:     at runMicrotasks (<anonymous>)
2020-05-18 21:55:27.716  - [31merror[39m: host.raspi4 Caught by controller[1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-05-18 21:55:27.720  - [31merror[39m: host.raspi4 instance system.adapter.sql.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2020-05-18 21:55:27.721  - [32minfo[39m: host.raspi4 Restart adapter system.adapter.sql.0 because enabled

```

JS Controller 3.1.4
nodejs: 12.16.3
npm: 6.14.4

**Comment by sbormann** [comment]
+1

**Comment by Xsev1** [comment]
+1

**Comment by Apollon77** [comment]
Please go back to latest 1.12.x till fix is done hopefully later today

**Comment by m-s-b** [comment]
Got the same error after installing 1.13.0. After downgrade to 1.12.5:
`sql.0	2020-05-19 07:34:49.602	info	(4756) No Data
sql.0	2020-05-19 07:34:24.964	error	(4756) Error: Packets out of order. Got: 1 Expected: 0`
Actually I´m not able to connect to SQL database.

**Comment by jens-maus** [comment]
same problem here with 1.13.0. After downgrade to 1.12.5 everything works again.

**Comment by Apollon77** [comment]
on my list for today

**Comment by Apollon77** [comment]
please check 1.13.1!!

**Comment by m-s-b** [comment]
Adapter ist grün und Daten werden auch gespeichert. 
Allerdings wie in issue #122 Warnungen "no Real ID" für diverse Datenpunkte von linkeddevices und sourceanalytics. 
Zusätzlich nach jedem Adapterstart ~ 20 mal die Warnung "No connection to database" obwohl der Test in der Adapterkonfiguration funktioniert.

**Comment by Apollon77** [comment]
Bitte auch hier wie in #122 abgefragt mal schauen was exakt das für states sind die er da anmeckert ... alle Details helfen weil wir es bisher nicht nachstellen können. Wir haben de crash grund jetzt verhindert - aber verstehen Ihn noch nicht.

"No connection to database" ... Logs? Am besten mal debug log bitte aber in ein eigenes issue

**Comment by Apollon77** [comment]
weiter in #122
