### ISSUE TITLE
Connection to PostgreSQL fails due to relative file paths

### ISSUE THREAD

**Issue by Damian411** [ioBroker/ioBroker.sql#285]
**Describe the bug**  
It is not possible to connect to a PostgreSQL database (CCU-historian), because the adapter seems to use relative file paths, even if absolute are configured. With e. g. Grafana a connection to the PostgreSQL database works as expected.

**To Reproduce**  
Select "PostgreSQL" in iobroker.sql instance, fill out the fields and configure an absolute file path ("/database/history") and click on "Test connection". 
It appears an error popup "Error: Connection terminated unexpectedly".

In the database appears that messages: 
`2022-12-28T07:26:49.657498340Z org.h2.message.DbException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:postgres". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-212]
2022-12-28T07:26:49.657525002Z 	at org.h2.message.DbException.get(DbException.java:223)
2022-12-28T07:26:49.657531277Z 	at org.h2.message.DbException.get(DbException.java:199)
2022-12-28T07:26:49.657535934Z 	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:464)
2022-12-28T07:26:49.657540428Z 	at org.h2.engine.Engine.openSession(Engine.java:49)
2022-12-28T07:26:49.657544873Z 	at org.h2.engine.Engine.openSession(Engine.java:222)
2022-12-28T07:26:49.657549338Z 	at org.h2.engine.Engine.createSession(Engine.java:201)
2022-12-28T07:26:49.657555147Z 	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:292)
2022-12-28T07:26:49.657560031Z 	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:140)
2022-12-28T07:26:49.657593915Z 	at java.base/java.lang.Thread.run(Unknown Source)
2022-12-28T07:26:49.657691017Z Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:postgres". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-212]
2022-12-28T07:26:49.657705959Z 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
2022-12-28T07:26:49.657714193Z 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
2022-12-28T07:26:49.657721525Z 	... 9 more`

**Expected behavior**  
A successfully connect to PostgreSQL database.

**Screenshots & Logfiles**  
Two screenshot attached.

**Versions:**  
 - Adapter version: 2.20
 - JS-Controller version: 4.0.23
 - Node version: v16.19.0
 - Operating system: Ubuntu 22.04.1 LTS

De- and reinstall of the instance did not solve it.

![sql error](https://user-images.githubusercontent.com/32341615/209778808-64dc8bf6-8907-424f-99f2-4c0d00b6a4dc.jpg)
![sql config](https://user-images.githubusercontent.com/32341615/209778821-18787833-c822-4c84-91bf-e7e12d68d127.jpg)

**Comment by Apollon77** [comment]
Des it work when you save the config and just the "test" is the issue?

The database name is not used for the connection check at all ... and as you can see in the settings there is no file path provided at all

> {"server":"10.0.100.130","host":"10.0.100.130","user":"sa","password":"****","max_idle":2,"max_active":101,"max_wait":10000,"when_exhausted":"block","port":5435,"database":"postgres"}

So, is there a requirement based on your Postgres configuration?

**Comment by Damian411** [comment]
The instance stays with an error in "Connected to device or service":


![iobroker sql error](https://user-images.githubusercontent.com/32341615/210087859-25fb6cfb-dd86-49c7-9421-0fabc957a384.jpg)


Alternatively in CCU-Historian a JSON-RPC interface exists, but I would prefer a SQL query.

**Comment by Apollon77** [comment]
What does the Log on server says? The same error as when testing?

How does the postgresql configuration looks like?

**Comment by Apollon77** [comment]
PS: did you tried to enter the "database name" without the leading "/" ?

**Comment by Damian411** [comment]
It generate the same error message on the database server.
I tried different database names, also without the "/", nothing works.
I will check the Postgre Config tommorrow.

**Comment by Damian411** [comment]
In CCU-Historian following options are configured for Postgre:

database.pgEnable: true
database.pgPort: 5435 (Default)
database.pgAllowOthers: true

More information 
https://github.com/mdzio/ccu-historian/wiki#liste-aller-optionen

**Comment by Apollon77** [comment]
Ok where is the db name configuration?

Is the postgresql server having anything in it's log when iobroker accesses to maybe see details of the error?

**Comment by Apollon77** [comment]
Also wenn ich dfas bei CCU-Historian pberfliege würde ich fragen was genau im Call auf die DB Shcnittstelle als Datenbank gesetzt werden muss. Da sist aber keien iobroker sondern eine CCU Historian Frage!

**Comment by Damian411** [comment]
Das Datenbank Verzeichnis steht in der CCU-Historian Config:
database.dir='/database'
Dort wird die Datenbank namens "history" erzeugt, die ich im Dateisystem auch sehen kann.
Ich habe zwischenzeitlich auch einen TCPdump gezogen und gesehen, dass bei iobroker.sql Benutzername, Passwort und "database postgres" gesendet wird. 
Grafana sendet "database /database/history". Bei Grafana funktionieren die Verbindung und die SQL Abfragen. 

Ich vermute also, dass iobroker fälschlicherweise "database postgres" statt dem Wert im Textfeld überträgt und die Verbindung daher fehlschlägt. Die Fehlermeldung auf dem CCU-Historian ist dann m. E. auch logisch, da der Pfad "postgres" kein absoluter Pfad ist.

**Comment by Apollon77** [comment]
> Ich vermute also, dass iobroker fälschlicherweise "database postgres" statt dem Wert im Textfeld überträgt und die Verbindung daher fehlschlägt. Die Fehlermeldung auf dem CCU-Historian ist dann m. E. auch logisch, da der Pfad "postgres" kein absoluter Pfad ist.

Beim CInnectiontest ist dies korrekt das das so ist weil der dbname nicht gesendet wird. Den Bug kann ich fixen.

ALso bitte dann mal nach speochern der Konfiguration die Instanz auf Debug log stellen ... Weil interessant ist was gesendet wird wenn der adapter mit der gespeicherten Konfig startet ... dann sollte da kein postgres gesendet werden.Und das sollte man im debug log sehen

**Comment by Damian411** [comment]
Gerne, hier die Log-Daten im Silly Modus:

![iobroker sql debug](https://user-images.githubusercontent.com/32341615/210129506-68410b8c-9edb-4538-8a25-d15b52fc02e0.png)
