### ISSUE TITLE
Cannot read property 'changesOnly' of undefined

### ISSUE THREAD

**Issue by vladitep** [ioBroker/ioBroker.sql#39]
does not start after update to latest version, with error:
Caught 2018-02-01 14:45:48.906 error by controller[1]: TypeError: Cannot read property 'changesOnly' of undefined

**Comment by GermanBluefox** [comment]
Here is the stack:
```
host.domoticz 2018-02-01 14:45:48.908 error instance system.adapter.sql.0 terminated with code 0 (OK)
Caught 2018-02-01 14:45:48.908 error by controller[1]: at Decoder. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught 2018-02-01 14:45:48.908 error by controller[1]: at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
Caught 2018-02-01 14:45:48.908 error by controller[1]: at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
Caught 2018-02-01 14:45:48.907 error by controller[1]: at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught 2018-02-01 14:45:48.907 error by controller[1]: at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
Caught 2018-02-01 14:45:48.907 error by controller[1]: at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
Caught 2018-02-01 14:45:48.907 error by controller[1]: at Socket. (/opt/iobroker/node_modules/iobroker.sql/main.js:932:13)
Caught 2018-02-01 14:45:48.907 error by controller[1]: at writeNulls (/opt/iobroker/node_modules/iobroker.sql/main.js:809:17)
Caught 2018-02-01 14:45:48.906 error by controller[1]: at writeNulls (/opt/iobroker/node_modules/iobroker.sql/main.js:816:13)
Caught 2018-02-01 14:45:48.906 error by controller[1]: at processStartValues (/opt/iobroker/node_modules/iobroker.sql/main.js:774:47)
Caught 2018-02-01 14:45:48.906 error by controller[1]: TypeError: Cannot read property 'changesOnly' of undefined
```

**Comment by Apollon77** [comment]
please try 1.6.7
